version: "3.7"

services:
  app:
    container_name: statistic_service
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    command: run
    volumes:
      - .:/app/
    env_file:
      - .env
    ports:
      - 127.0.0.1:8005:8005
    expose:
      - 8005
    links:
      - db
    depends_on:
      - db

  db:
    container_name: fastapi_db
    restart: always
    image: postgres:12.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      .env
    ports:
      - 5435:5432

volumes:
  postgres-data: